# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    unnecessary_this: true
    avoid_print: true
    empty_statements: true
    iterable_contains_unrelated_type: true
    literal_only_boolean_expressions: true
    always_specify_types: true
    avoid_as: true
    await_only_futures: true
    empty_catches: true
    file_names: true
    prefer_expression_function_bodies: true
    prefer_single_quotes: true
